on:
    push:
      branches:
        - master
  
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Display working directory
          run: pwd
        - name: printing folder contents
          run: ls
  
        - name: Print a message
          run: echo "shahd"
       