on:
    push:
      branches:
        - master
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Testing GitHub action
          run: pwd
  
        - name: Testing printing
          run: echo "shahd"
  